name: petshopapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.5.3
  quickalert: ^1.1.0
  cached_network_image: ^3.3.1
  sqflite: ^2.4.2
  path: ^1.9.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.2
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - images/main1.jpg
    - images/login.jpg
    - images/logo.png
    - images/section1.jpg
    - images/section2.jpg
    - images/section3.jpg
    - images/section4.jpg
    - images/shop.jpg
    - images/shop.png
    - images/shop1.jpg
    - images/shopori.jpg
    - images/back1.jpg
    - images/back2.png
    - images/back3.png
    - images/mainback1.avif
    - images/mainback2.avif
    - images/mainback3.avif
    - images/cattoy1.webp
    - images/cattoy2.jpg
    - images/cattoy3.jpg
    - images/cattoy4.jpg
    - images/cattoy5.jpg
    - images/cattoy6.jpg
    - images/cattoy7.jpg
    - images/cattoy8.webp
    - images/cattoy9.jpg
    - images/delete.png
    - images/dog_food1.jpg
    - images/dog_food2.jpg
    - images/dog_food3.jpg
    - images/dog_food4.jpg
    - images/dog_food5.jpg
    - images/dog_food6.jpg
    - images/dog_food7.jpg
    - images/dog_food8.jpg
    - images/dog_food9.jpg
    - images/dog_toy1.jpg
    - images/dog_toy2.webp
    - images/dog_toy3.webp
    - images/dog_toy4.webp
    - images/dog_toy5.jpg
    - images/dog_toy6.jpg
    - images/dog_toy7.jpg
    - images/dog_toy8.webp
    - images/dog_toy9.jpg
    - images/about.jpg
    - images/facebook.png
    - images/instagram.png